version: "3"

services:
  speedcard:
    image: php:7.2-apache
    restart: always
    volumes:
      - ./src/:/var/www/html
    networks:
      - caddy-net

networks:
  caddy-net:
    external: True
